#!/usr/bin/env python3
#
# Copyright (C) 2017 The University of Sheffield, UK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

"""Tool for extracting crx file from a tar archive."""

import os
import sys
import getopt
import tarfile
import datetime
import dateutil
import dateutil.parser
from ExtensionCrawler.archive import last_crx, get_local_archive_dir

# Script should run with python 3.4 or 3.5
assert sys.version_info >= (3, 4) and sys.version_info < (3, 6)


def helpmsg():
    """Print help message."""
    print("extract-crx [OPTION] extid")
    print("    -h        print this help text")
    print("    -s        silent (no log messages)")
    print("    -d=<DATE> date")
    print("    -o=<DIR>  output directory")
    print("    -a=<DIR>  archive directory")


def get_tarinfo(members, last):
    for tarinfo in members:
        if tarinfo.name == last:
            yield tarinfo



def main(argv):
    """Main function of the extension crawler."""
    basedir = "archive"
    verbose = True
    date = None
    extid = ""
    output = ""
    try:
        opts, args = getopt.getopt(argv, "hsd:a:o:", ["date=", "archive=", "output="])
    except getopt.GetoptError:
        helpmsg()
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            helpmsg()
            sys.exit()
        elif opt in ("-a", "--archive"):
            basedir = arg
        elif opt in ("-d", "--date"):
            date = arg
        elif opt in ("-o", "--output"):
            output = arg
        elif opt == '-s':
            verbose = False

    if len(args) > 0:
        extid = args[0]
    else:
        help()
        sys.exit()

    if date is not None:
        dateobj = dateutil.parser.parse(date)
        if dateobj.tzinfo is None or dateobj.tzinfo.utcoffset(dateobj) is None:
            dateobj = dateobj.replace(tzinfo=datetime.timezone.utc)
        last = last_crx(os.path.join(basedir, "data"), extid, dateobj)
    else:
        last = last_crx(os.path.join(basedir, "data"), extid)

    if last != "":
        tar = os.path.join(basedir, "data",
                           get_local_archive_dir(extid), extid + ".tar")
        if os.path.exists(tar):
            if verbose:
                print("Extracting "+os.path.join(output, last))
            with tarfile.open(tar, 'r') as archive:
                archive.extractall(path=output, members=get_tarinfo(archive, last))

if __name__ == "__main__":
    main(sys.argv[1:])
