#!/bin/bash
set -o nounset
set -x

SING_EXEC="singularity exec --pwd /opt/ExtensionCrawler -B $TMPDIR:/tmp $SING_IMG"

printenv
echo "The following parameter were passed: $*"
echo "Printing the content of $ARCHIVE to force mounting:"
ls "$ARCHIVE"

if [ -f "$BASEDIR/ids" ]; then
  EXT_SELECT="-e $BASEDIR/ids"
else
  EXT_SELECT=
fi


/usr/bin/time $SING_EXEC ./create-db -t 1 -a "$ARCHIVE" -n $SGE_TASK_ID -N $MAX_SGE_TASK_ID $EXT_SELECT $*
